# Generated by Django 4.2.7 on 2025-04-23 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.IntegerField()),
                ("total_price", models.FloatField()),
                ("order_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
